# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lixtecapiapplication:
    image: lixtecapiapplication
    build:
      context: .
      dockerfile: API/LixTec.Api.Application/Dockerfile
    ports:
      - 20000:20000
